version: '3'
services:
  # Elasticsearch 节点
  elasticsearch:
    image: elasticsearch:8.11.1  # 使用较新的 8.x 版本
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"       # 单节点模式，学习够用了
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"   # 限制内存，防止把电脑卡死
      - "xpack.security.enabled=false"     # ⚠️ 学习阶段关闭安全验证，生产环境严禁关闭！
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200" # HTTP 端口，Java 程序和 Postman 连这个
      - "9300:9300" # TCP 端口，集群通信用
    networks:
      - ai-search-net

  # Kibana 可视化界面
  kibana:
    image: kibana:8.11.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 # 指向 ES
    ports:
      - "5601:5601" # 浏览器访问端口
    depends_on:
      - elasticsearch
    networks:
      - ai-search-net

  postgres:
    # 注意：这里必须用 postgis 镜像，否则无法使用地理位置函数
    image: postgis/postgis:16-3.4
    container_name: pg
    environment:
      POSTGRES_USER: myuser         # 数据库用户名
      POSTGRES_PASSWORD: mypassword # 数据库密码
      POSTGRES_DB: local_life       # 默认创建的数据库名
      TZ: Asia/Shanghai
    ports:
      - "5432:5432"
    security_opt:
      - seccomp:unconfined
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - ai-search-net

  redis:
    image: redis:latest
    container_name: ai_redis
    # 开启持久化，并设置密码为 "mypassword"
    command: redis-server --appendonly yes --requirepass "mypassword"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-search-net

volumes:
  es_data:
  pg_data:
  redis_data:

networks:
  ai-search-net:
    driver: bridge